"""
Standard Malaysian SME chart of accounts (SSM/accountant-provided, Aug 2026).

215 accounts using the first-digit nature convention: 1 Asset, 2 Liability,
3 Equity, 4 Revenue, 5 Cost of Sales, 6 Expense, 8 Other Income,
9 Other Expense. 'H' rows from the source file become header/subheader
roles (top x0000 sections = header, other groups = subheader).
Loaded per-org via POST /accounts/import-standard-chart (idempotent).
"""

# (code, name, type, account_role)
STANDARD_CHART_MY: list[tuple[str, str, str, str]] = [
    ("10000", "Assets", "asset", "header"),
    ("11000", "PROPERTY, PLANT & EQUIPMENTS", "asset", "subheader"),
    ("11100", "Freehold Property", "asset", "subheader"),
    ("11110", "Freehold Property - Cost", "asset", "account"),
    ("11111", "Freehold Property - Acc Depn", "asset", "account"),
    ("11200", "Leasehold Property", "asset", "subheader"),
    ("11210", "Leasehold Property - Cost", "asset", "account"),
    ("11211", "Leasehold Propoerty - Acc Depn", "asset", "account"),
    ("11300", "Plant & Machinery", "asset", "subheader"),
    ("11310", "Plant & Machinery - Cost", "asset", "account"),
    ("11311", "Plant & Machinery - Acc Depn", "asset", "account"),
    ("11400", "Motor Vehicles", "asset", "subheader"),
    ("11410", "Motor Vehicles - Cost", "asset", "account"),
    ("11411", "Motor Vehicles - Acc Depn", "asset", "account"),
    ("11500", "Furniture & Fitting", "asset", "subheader"),
    ("11510", "Furniture & Fitting - Cost", "asset", "account"),
    ("11511", "Furniture & Fitting - Acc Depn", "asset", "account"),
    ("11600", "Office Equipment", "asset", "subheader"),
    ("11610", "Office Equipment - Cost", "asset", "account"),
    ("11611", "Office Equipment - Acc Depn", "asset", "account"),
    ("11700", "Computers", "asset", "subheader"),
    ("11710", "Computer - Cost", "asset", "account"),
    ("11711", "Computer - Acc Depn", "asset", "account"),
    ("12000", "CURRENT ASSETS", "asset", "subheader"),
    ("12100", "Inventories", "asset", "subheader"),
    ("12110", "Inventories", "asset", "account"),
    ("12300", "Trade Receivables", "asset", "subheader"),
    ("12310", "Trade Receivables", "asset", "account"),
    ("12399", "Allowance for Doubtful Debt", "asset", "account"),
    ("12400", "Non-Trade Receivables", "asset", "subheader"),
    ("12410", "Deposits Recoverable", "asset", "account"),
    ("12420", "Prepayments", "asset", "account"),
    ("12430", "Advances", "asset", "account"),
    ("12440", "Others Receivables", "asset", "account"),
    ("12500", "Fixed Deposits", "asset", "subheader"),
    ("12510", "FD - Licensed Bank", "asset", "account"),
    ("12520", "FD - Licensed Finance Company", "asset", "account"),
    ("12600", "Cash & Bank Balances", "asset", "subheader"),
    ("12610", "Bank", "asset", "account"),
    ("12620", "Cash in hand", "asset", "account"),
    ("12630", "Undeposited Funds", "asset", "account"),
    ("12640", "Clearing Account", "asset", "account"),
    ("20000", "Liabilities", "liability", "header"),
    ("21000", "CURRENT LIABILITIES", "liability", "subheader"),
    ("21100", "Trade Payables", "liability", "subheader"),
    ("21110", "Trade Payables", "liability", "account"),
    ("21200", "Non-Trade Payables", "liability", "subheader"),
    ("21210", "Client Deposit Accounts", "liability", "account"),
    ("21220", "Payroll Payables", "liability", "account"),
    ("21221", "EPF Payables", "liability", "account"),
    ("21222", "SOCSO Payables", "liability", "account"),
    ("21223", "STD Payables", "liability", "account"),
    ("21224", "Employees' Advances", "liability", "account"),
    ("21230", "Others Payables", "liability", "account"),
    ("21240", "Accrued Expenses", "liability", "account"),
    ("21250", "Provisions", "liability", "account"),
    ("21300", "Amount Due To Directors", "liability", "subheader"),
    ("21310", "Amount Due to Director 1", "liability", "account"),
    ("21400", "Tax Liabilities", "liability", "subheader"),
    ("21410", "Tax Liabilities - Prior Years", "liability", "account"),
    ("21420", "Tax Liabilities - Current Year", "liability", "account"),
    ("21500", "Finance Lease Liabilities", "liability", "subheader"),
    ("21510", "HP - [ ]", "liability", "account"),
    ("21515", "HP - Int Suspense - [ ]", "liability", "account"),
    ("22000", "LONG TERM LIABILITIES", "liability", "subheader"),
    ("22100", "Long Term Borrowings", "liability", "subheader"),
    ("22110", "Term Loans", "liability", "subheader"),
    ("22111", "Term Loans", "liability", "account"),
    ("22200", "Finance Lease Liabilities", "liability", "subheader"),
    ("22211", "HP - Long Term", "liability", "account"),
    ("22300", "Deferred Tax Liabilities", "liability", "subheader"),
    ("22310", "Deferred Tax Liabilities", "liability", "account"),
    ("22400", "Sale and Service Tax Payables", "liability", "subheader"),
    ("22410", "Service Tax Payables", "liability", "account"),
    ("30000", "Equity", "equity", "header"),
    ("31000", "SHARE CAPITAL", "equity", "account"),
    ("32000", "ACCUMULATED PROFIT", "equity", "subheader"),
    ("32100", "Retained Earnings", "equity", "account"),
    ("32200", "Profit for the financial year", "equity", "account"),
    ("32999", "Historical Balancing", "equity", "account"),
    ("40000", "Income", "revenue", "header"),
    ("41000", "Trading Revenue", "revenue", "subheader"),
    ("41100", "Trading Revenue", "revenue", "account"),
    ("42000", "Contract Income", "revenue", "subheader"),
    ("42100", "Contract Income", "revenue", "account"),
    ("43000", "Commission", "revenue", "subheader"),
    ("43100", "Commission income", "revenue", "account"),
    ("49999", "Currency Gain Loss", "revenue", "account"),
    ("50000", "Cost Of Sales", "cost_of_sales", "header"),
    ("51000", "Inventories", "cost_of_sales", "subheader"),
    ("51100", "Opening Inventories", "cost_of_sales", "account"),
    ("51200", "Purchases", "cost_of_sales", "account"),
    ("51300", "Closing Inventories", "cost_of_sales", "account"),
    ("52000", "Direct Overhead Costs", "cost_of_sales", "subheader"),
    ("52100", "Staff Costs", "cost_of_sales", "subheader"),
    ("52110", "Salary & Wages", "cost_of_sales", "account"),
    ("52120", "Bonus", "cost_of_sales", "account"),
    ("52130", "EPF Contribution", "cost_of_sales", "account"),
    ("52131", "SOCSO contribution", "cost_of_sales", "account"),
    ("52140", "Overtime Claims", "cost_of_sales", "account"),
    ("52149", "Medical Expenses", "cost_of_sales", "account"),
    ("52150", "Contract Labours Wages", "cost_of_sales", "account"),
    ("52160", "Travelling & Accomodation", "cost_of_sales", "account"),
    ("52170", "Workers Amenities & Welfare", "cost_of_sales", "account"),
    ("53100", "Transportation", "cost_of_sales", "subheader"),
    ("53110", "Carriage Inwards", "cost_of_sales", "account"),
    ("53120", "Carriage Outwards", "cost_of_sales", "account"),
    ("53130", "Insurance - Marine", "cost_of_sales", "account"),
    ("53140", "Parking & Toll", "cost_of_sales", "account"),
    ("53150", "Petrol", "cost_of_sales", "account"),
    ("54100", "Rental", "cost_of_sales", "subheader"),
    ("54110", "Rental of Factory", "cost_of_sales", "account"),
    ("55100", "Upkeeping Costs", "cost_of_sales", "subheader"),
    ("55110", "Upkeep of Factory", "cost_of_sales", "account"),
    ("55120", "Upkeep of Machinery/Equipment", "cost_of_sales", "account"),
    ("56100", "Factory Overhead", "cost_of_sales", "subheader"),
    ("56110", "Water & Electricity", "cost_of_sales", "account"),
    ("56120", "Sundry Expenses", "cost_of_sales", "account"),
    ("59000", "Work In Progress", "cost_of_sales", "subheader"),
    ("59100", "Opening of WIP", "cost_of_sales", "account"),
    ("59200", "Closing WIP", "cost_of_sales", "account"),
    ("60000", "Expenses", "expense", "header"),
    ("61000", "STAFF COST", "expense", "subheader"),
    ("61100", "Payroll", "expense", "subheader"),
    ("61110", "Bonus", "expense", "account"),
    ("61120", "Salaries", "expense", "account"),
    ("61130", "Overtime", "expense", "account"),
    ("61140", "Allowances", "expense", "account"),
    ("61200", "Directors Remuneration", "expense", "subheader"),
    ("61210", "Director Fees", "expense", "account"),
    ("61220", "Director Salary & Bonus", "expense", "account"),
    ("61300", "Staff Statutory Contribution", "expense", "subheader"),
    ("61310", "EPF Contribution", "expense", "account"),
    ("61320", "SOCSO Contribution", "expense", "account"),
    ("61400", "Staff Benefits", "expense", "subheader"),
    ("61410", "Entertainment - Staff", "expense", "account"),
    ("61420", "Medical Expenses", "expense", "account"),
    ("61430", "Staff Amenities & Welfare", "expense", "account"),
    ("61440", "Training & Seminar", "expense", "account"),
    ("61450", "Travelling & Accomodation", "expense", "account"),
    ("61460", "Other Employer Expenses", "expense", "account"),
    ("62000", "SELLING & DISTRIBUTION", "expense", "subheader"),
    ("62100", "Entertainment", "expense", "subheader"),
    ("62110", "Entertainment - Client", "expense", "account"),
    ("62120", "Entertainment - Supplier", "expense", "account"),
    ("62200", "Travelling", "expense", "subheader"),
    ("62210", "Car Rental", "expense", "account"),
    ("62220", "Insurance & Road Tax", "expense", "account"),
    ("62230", "Petrol Charges", "expense", "account"),
    ("62240", "Parking & Toll", "expense", "account"),
    ("62250", "Upkeep of Motor Vehicle", "expense", "account"),
    ("62300", "Promotional Cost", "expense", "subheader"),
    ("62310", "Advertising & Promotion", "expense", "account"),
    ("62400", "Collection", "expense", "subheader"),
    ("62410", "Bad Debt Written-Off", "expense", "account"),
    ("62420", "Allown for Doubtful Debt - TD", "expense", "account"),
    ("62421", "Allown for Doubtful Debt - NTD", "expense", "account"),
    ("63000", "PPE RELATED COST", "expense", "subheader"),
    ("63100", "Depreciation", "expense", "subheader"),
    ("63110", "Depn - Freehold Property", "expense", "account"),
    ("63120", "Depn - Leasehold Property", "expense", "account"),
    ("63130", "Depn - Plant & Machinery", "expense", "account"),
    ("63140", "Depn - Motor Vehicles", "expense", "account"),
    ("63150", "Depn - Furniture & Fitting", "expense", "account"),
    ("63160", "Depn - Office Equipment", "expense", "account"),
    ("63170", "Depn - Computer", "expense", "account"),
    ("63200", "PPE Disposal", "expense", "subheader"),
    ("63210", "PPE Written-Off", "expense", "account"),
    ("63220", "Loss on Disposal of PPE", "expense", "account"),
    ("64000", "OTHER OPERATING COST", "expense", "subheader"),
    ("64100", "Administrative", "expense", "subheader"),
    ("64110", "Courier Charges", "expense", "account"),
    ("64120", "Fines & Penalty", "expense", "account"),
    ("64130", "Newspaper & Periodicals", "expense", "account"),
    ("64140", "Postages", "expense", "account"),
    ("64150", "Printing & Stationery", "expense", "account"),
    ("64160", "Sundry Expenses", "expense", "account"),
    ("64170", "Gift & Donation - TD", "expense", "account"),
    ("64171", "Gift & Donation - NTD", "expense", "account"),
    ("64200", "Office Overhead", "expense", "subheader"),
    ("64210", "Electricity & Water Charges", "expense", "account"),
    ("64220", "Office Rental", "expense", "account"),
    ("64230", "Telephone & Fax Charges", "expense", "account"),
    ("64240", "Upkeep of Office Premises", "expense", "account"),
    ("64250", "Upkeep of Computer & Equipment", "expense", "account"),
    ("64260", "Quit Rent", "expense", "account"),
    ("64300", "Professional Fees", "expense", "subheader"),
    ("64310", "Accounting Fees", "expense", "account"),
    ("64320", "Audit Fee - Current Year", "expense", "account"),
    ("64321", "Audit Fee - Prior Years", "expense", "account"),
    ("64330", "Secretarial Fees", "expense", "account"),
    ("64340", "Tax Agent Fees", "expense", "account"),
    ("64350", "Incorporation Expenses", "expense", "account"),
    ("64351", "Legal Fee - Revenue Nature", "expense", "account"),
    ("64352", "Legal Fee - Capital Nature", "expense", "account"),
    ("80000", "Other Income", "other_income", "header"),
    ("81000", "Reliased Gain", "other_income", "subheader"),
    ("81100", "Gain on Disposal of PPE", "other_income", "account"),
    ("81200", "Forex - Realised", "other_income", "account"),
    ("81300", "Interest Received", "other_income", "account"),
    ("81400", "Rental Income", "other_income", "account"),
    ("81500", "Other Income", "other_income", "account"),
    ("82000", "Unreliased Gain", "other_income", "subheader"),
    ("82100", "Forex - Unrealised", "other_income", "account"),
    ("90000", "Other Expenses", "other_expense", "header"),
    ("91000", "FINANCE COST", "other_expense", "subheader"),
    ("91100", "Bank Overdraft Interest", "other_expense", "account"),
    ("91200", "Finance Lease Interest", "other_expense", "account"),
    ("91300", "Hire Purchase Interest", "other_expense", "account"),
    ("91400", "Trust Receipt Interest", "other_expense", "account"),
    ("91500", "Other Bank Charges", "other_expense", "account"),
    ("92000", "TAXATION", "other_expense", "subheader"),
    ("92100", "Taxation for the Year", "other_expense", "account"),
    ("92200", "Deferred Tax", "other_expense", "account"),
]
